# Generated by Django 3.2.12 on 2022-06-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.CharField(default='Some String', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.CharField(default='Some String', max_length=200),
        ),
    ]
