# Generated by Django 3.2.12 on 2022-06-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220620_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vaccine',
            field=models.CharField(default='Some String', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(max_length=200),
        ),
    ]
